### ISSUE TITLE
Salad Builder server build error

### ISSUE THREAD

**Issue by badlydrawnrob** [jfairbank/programming-elm.com#16]
> **🚀 Edit: Don't use webpack, use `elm-watch` (or try parcel/vite)** (see [below](https://github.com/jfairbank/programming-elm.com/issues/16#issuecomment-3194657263) conversation)
> **🐁 Future chapters can also use `esbuild` to compile react files** for a lighter setup (see issue #17).

I'm getting a lot of deprecated, "run `npm audit fix`", and server errors when trying to install and start the Salad Builder (Chapter 6: Build Larger Applications) — wasn't sure where else to post this. I imagine you've not looked at this book in a while, but would be great to get feedback as there's _many_ dependencies and I wouldn't even know where to start! Using Node v20.18.0.

```terminal
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/rob/Sites/GitHub/elm-playground/programming-elm/salad-builder/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/rob/Sites/GitHub/elm-playground/programming-elm/salad-builder/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/rob/Sites/GitHub/elm-playground/programming-elm/salad-builder/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/rob/Sites/GitHub/elm-playground/programming-elm/salad-builder/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/rob/Sites/GitHub/elm-playground/programming-elm/salad-builder/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/rob/Sites/GitHub/elm-playground/programming-elm/salad-builder/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/rob/Sites/GitHub/elm-playground/programming-elm/salad-builder/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/rob/Sites/GitHub/elm-playground/programming-elm/salad-builder/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/rob/Sites/GitHub/elm-playground/programming-elm/salad-builder/scripts/start.js:19
  throw err;
  ^
...
}
```

**Comment by pakx** [comment]
These look like webpack issues.
If you've been unable to resolve them, imo move to vite, instructions below:

- current node LTS (22.17.1)
- elm 0.19.1 installed globally

- create file project-root/vite.config.mjs (<-- note .mjs)

  ```js
  import { defineConfig } from 'vite';
  import elmPlugin from 'vite-plugin-elm';

  export default defineConfig({
    plugins: [elmPlugin()]
  });
   ```

- move /public/(index.html, favicon.ico) to /; this is default for vite wrt indx.html; w/ original file placements vite seems not to "see" elm file edits even after fiddling w/ vite.config.mjs
- index.html
  - fix up reference to favicon
  - add `<script type="module" src="/src/index.js"></script>` ; this loads index.js, which itself loads css, loads elm, and initializes app
- delete node_modules
- delete package-lock.json
- replace *package.json* w/ the following minimal version, using this combination of vite + vite-plugin-elm versions as current latest has console warnings

  ```js
  {
    "scripts": {
        "start": "vite",
        "test": "elm-test"
    },
    "devDependencies": {
        "vite": "5.0.0",
        "vite-plugin-elm": "3.0.0"
    }
  }
   ```

- run `npm install`

Usage:

- run `npm run start`; this starts vite, which prints a localhost url to console
- open the url in a (modern) browser
- vite should pick up on edits to assets (html, elm, etc) and automatically push to browser

**Comment by pakx** [comment]
Or move to parcel, for even less ceremony and configuration. Here's a video comparing vite vs parcel for elm development: https://www.youtube.com/watch?v=I7a96HHfsME

**Comment by badlydrawnrob** [comment]
@pakx Thank you for getting back to me on this!

I think Elm Land uses vite, but in this case it doesn't seem like you need _either_ of those. I didn't realise it's literally only a server; I thought the API was built out with javascript, but the bulk of the work is done with the `https://programming-elm.com/salad/send` endpoint.

**For beginners I think this just convolutes things**, so I [boiled it down to the absolute essentials](https://github.com/badlydrawnrob/elm-playground/tree/master/programming-elm/06-build-larger-apps) ...

1. **`npx elm-watch hot`** for live reload with [elm watch](https://lydell.github.io/elm-watch/getting-started/)
    - This gives you live error checking
2. **`elm reactor`** and view the app at `build/index.html`
    - You can build with `npx elm-watch make --optimize`, or the regular `elm make` way.

This is one of the reasons I dislike javascript, 45 dependencies (and _their_ dependencies) just to get a flippin' server running, with rapid package updates, so everything's likely to break next month! There's other simple servers like [`live-server`](https://www.npmjs.com/package/live-server) (and I'm sure many others), but in this case Elm Watch does everything we want it to do. A [beta static server](https://lydell.github.io/elm-watch/server/) is coming too.

I'd much prefer to stay within the Elm world, or only utilize complicated javascript/packages when it's absolutely necessary. If you ever rewrite the book, that would be my suggestion!

Thanks again for taking the time. Hope this helps others.
